import Splash from './Splash';
import Login from './Login';
import Register from './Register';
import WelcomeAuth from './WelcomeAuth';
import HomeScreen from './HomeScreen';
import Akun from './Akun';
import List from './List';
import RankingLaptop from './Ranking';
import ViewData from './ViewData';
import ViewDataScore from './ViewData/ViewDataScore';
import InputData from './InputData';
import InputDataKebutuhan from './InputData/InputKebutuhan';
import RekomendasiLaptop from './DataRekomendasi';
import DataKriteria from './DataKriteria';
import DataAlternatif from './DataAlternatif';
import DataPerhitungan from './DataPerhitungan';
export { Splash, Login, Register, WelcomeAuth,HomeScreen,Akun,List,RankingLaptop,ViewData,InputData,RekomendasiLaptop,ViewDataScore,InputDataKebutuhan,DataKriteria,DataAlternatif,DataPerhitungan};